// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgFT-VrKgx6H1dSpJ0I6wN9UlUnguQgSY',
    appId: '1:1026229447943:web:d2399b8ca2f5f7d22729a2',
    messagingSenderId: '1026229447943',
    projectId: 'lias-4336f',
    authDomain: 'lias-4336f.firebaseapp.com',
    storageBucket: 'lias-4336f.firebasestorage.app',
    measurementId: 'G-2YJKZ4MQB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkmv5ndyqbfRVlsuT5YiFMkdXd5LqD9V8',
    appId: '1:1026229447943:android:c65b09fdcf64cab32729a2',
    messagingSenderId: '1026229447943',
    projectId: 'lias-4336f',
    storageBucket: 'lias-4336f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB46lJtF0inOYX_FZbQ2EwnLCpsRnvnJCw',
    appId: '1:1026229447943:ios:3fe984224fca45892729a2',
    messagingSenderId: '1026229447943',
    projectId: 'lias-4336f',
    storageBucket: 'lias-4336f.firebasestorage.app',
    iosBundleId: 'com.example.lias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB46lJtF0inOYX_FZbQ2EwnLCpsRnvnJCw',
    appId: '1:1026229447943:ios:3fe984224fca45892729a2',
    messagingSenderId: '1026229447943',
    projectId: 'lias-4336f',
    storageBucket: 'lias-4336f.firebasestorage.app',
    iosBundleId: 'com.example.lias',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgFT-VrKgx6H1dSpJ0I6wN9UlUnguQgSY',
    appId: '1:1026229447943:web:182c00b0c7c8a91b2729a2',
    messagingSenderId: '1026229447943',
    projectId: 'lias-4336f',
    authDomain: 'lias-4336f.firebaseapp.com',
    storageBucket: 'lias-4336f.firebasestorage.app',
    measurementId: 'G-L8LZ9KDDG2',
  );
}
